export const PUT_COMPETITIONS = 'PUT_COMPETITIONS';
export const PUT_CURRENT_COMPETITION = 'PUT_CURRENT_COMPETITION';
export const PUT_CURRENT_COMPETITOR = 'PUT_CURRENT_COMPETITOR';
export const PUT_CURRENT_COMPETITOR_PER_STAGE = 'PUT_CURRENT_COMPETITOR_PER_STAGE';