export const PUT_COMPETITIONS = 'PUT_COMPETITIONS';
export const PUT_CURRENT_COMPETITION = 'PUT_CURRENT_COMPETITION';

export const PUT_CURRENT_OVERALL_RESULTS = 'PUT_CURRENT_OVERALL_RESULTS';
export const PUT_CURRENT_STAGE_VIEW_RESULTS = 'PUT_CURRENT_STAGE_VIEW_RESULTS';
export const PUT_CURRENT_COMPETITOR_VIEW_RESULTS = 'PUT_CURRENT_COMPETITOR_VIEW_RESULTS';

export const SET_VIEW_SWITCHER_OVERALL = 'SET_VIEW_SWITCHER_OVERALL';
export const SET_VIEW_SWITCHER_STAGE = 'SET_VIEW_SWITCHER_STAGE';
export const SET_VIEW_SWITCHER_COMPETITOR = 'SET_VIEW_SWITCHER_COMPETITOR';