export const PUT_COMPETITIONS = 'PUT_COMPETITIONS';
export const PUT_CURRENT_COMPETITION = 'PUT_CURRENT_COMPETITION';
export const PUT_CURRENT_COMPETITION_OVERALL_RESULTS = 'PUT_CURRENT_COMPETITION_OVERALL_RESULTS';
export const PUT_CURRENT_COMPETITION_STAGE_VIEW_RESULTS = 'PUT_CURRENT_COMPETITION_STAGE_VIEW_RESULTS';
export const PUT_CURRENT_COMPETITOR_PER_COMPETITION_RESULT = 'PUT_CURRENT_COMPETITOR_PER_COMPETITION_RESULT';
export const SET_VIEW_SWITCHER_OVERALL = 'SET_VIEW_SWITCHER_OVERALL';
export const SET_VIEW_SWITCHER_STAGE = 'SET_VIEW_SWITCHER_STAGE';